version: "3"

services:
  intel-irris:
    image: waziup/intel-irris-waziapp:latest
    container_name: waziup.intel-irris-waziapp
    build:
      context: ./
    volumes:
      #- /home/pi/waziup-gateway/apps/waziup/intel-irris-waziapp:/app/intel-irris-waziapp
      #- /var/lib/wazigate/apps/intel-irris-waziapp:/app/intel-irris-waziapp
      #- ./:/root/src/ # Uncomment for development
      - ./:/root/app # The unix socket has to have this name and be in ./ : proxy.sock
    ports:
      - "5000:5000"
    privileged: false
    restart: unless-stopped
    environment:
      - TEST_VAR=1
    healthcheck:
      test: curl --fail --unix-socket /var/lib/waziup/proxy.sock http://localhost/ || exit 1 #curl --fail http://localhost:5000/ || exit 1
      interval: 30s
      retries: 10 # Will try for 5 minutes
    network_mode: "host" # run app on {WaziGate IP}:5000/

networks:
  default:
    external:
      name: wazigate
